include "base/Protocol.thrift"
include "base/Result.thrift"
include "base/HostInfo.thrift"
include "order/OrderSearchService.thrift"
include "order/OrderApiService.thrift"
include "eureka/EurekaService.thrift"