host:
  ip: iris-cloud-gateway-1
  port: 30050
  serviceName: iris-cloud-gateway
  processId: 1
  defaultZone:
  - ip: iris-cloud-eureka-1
    port: 30001
  - ip: iris-cloud-eureka-2
    port: 30001
  - ip: iris-cloud-eureka-3
    port: 30001
  - ip: iris-cloud-eureka-4
    port: 30001